name: Feature Request
description: Suggest a new feature for SARAUDIO
labels: ['feature']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below.

  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen
      placeholder: |
        I would like to have support for WebRTC streaming...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Case
      description: Describe the use case for this feature
      placeholder: |
        In my application, I need to stream audio directly to a server in real-time...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: If you have ideas on how to implement this feature
      placeholder: |
        Add a new stage that converts audio frames to WebRTC format...

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        I've tried using MediaRecorder API but the latency is too high...

  - type: dropdown
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical for my use case
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Contribution
      options:
        - label: I am willing to help implement this feature
          required: false